### ISSUE TITLE
Bug: App crash on RecipeBook Fragment

### ISSUE THREAD

**Issue by steventango** [CMPUT301F22T02/well-fed#242]
Randomly I get the below exception when I open Recipe Fragment.

```FATAL EXCEPTION: main
Process: com.xffffff.wellfed, PID: 7733
java.lang.IllegalArgumentException: No view found for id 0x7f0800e9 (com.xffffff.wellfed:id/fragment_sort_container) for fragment SortingFragment{bbe338b} (ee68049e-06c4-4007-8f59-f262ce0794a3 id=0x7f0800e9)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)```

**Comment by Manpreet-Singh001** [comment]
@steventango this might be the issue
> 

This error also occurs when having nested Fragments and adding them with getSupportFragmentManager() instead of getChildFragmentManager().

https://stackoverflow.com/questions/7508044/android-fragment-no-view-found-for-id

**Comment by AkshatPandey1** [comment]
https://stackoverflow.com/questions/35090867/getchildfragmentmanager-cannot-be-resolved-or-cannot-be-referenced

Since we are using AppCompatActivity we won't be able to use that function instead of getSupportFragmentManager
