### ISSUE TITLE
Bug: Crash on Pixel 3a API 30

### ISSUE THREAD

**Issue by Manpreet-Singh001** [CMPUT301F22T02/well-fed#63]
App fails to launch on this device. Cause of error
```
Caused by: android.content.res.Resources$NotFoundException: Drawable com.example.wellfed:drawable/ic_mdi_carrot with resource ID #0x7f0700a0
2022-10-19 23:10:33.777 15911-15911/com.example.wellfed E/AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_mdi_carrot.xml from drawable resource ID #0x7f0700a0
```

**Comment by steventango** [comment]
Do you have [ic_mdi_carrot.xml](https://github.com/CMPUT301F22T02/well-fed/blob/main/app/src/main/res/drawable/ic_mdi_carrot.xml) in your local repository?

**Comment by Manpreet-Singh001** [comment]
> Do you have [ic_mdi_carrot.xml](https://github.com/CMPUT301F22T02/well-fed/blob/main/app/src/main/res/drawable/ic_mdi_carrot.xml) in your local repository?

yes, i do, the app runs fine on my samsung device plugged via a usb but fails on the emulator

**Comment by Manpreet-Singh001** [comment]
```
2022-10-19 23:20:25.292 16067-16090/com.example.wellfed E/DynamiteModule: Invalid GmsCore APK, remote loading disabled.
2022-10-19 23:20:25.298 16067-16090/com.example.wellfed E/DynamiteModule: Invalid GmsCore APK, remote loading disabled.
2022-10-19 23:20:25.569 16067-16067/com.example.wellfed E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.wellfed, PID: 16067
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.wellfed/com.example.wellfed.MainActivity}: android.view.InflateException: Binary XML file line #22 in com.example.wellfed:layout/activity_main: Binary XML file line #22 in com.example.wellfed:layout/activity_main: Error inflating class com.google.android.material.bottomappbar.BottomAppBar
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: android.view.InflateException: Binary XML file line #22 in com.example.wellfed:layout/activity_main: Binary XML file line #22 in com.example.wellfed:layout/activity_main: Error inflating class com.google.android.material.bottomappbar.BottomAppBar
     Caused by: android.view.InflateException: Binary XML file line #22 in com.example.wellfed:layout/activity_main: Error inflating class com.google.android.material.bottomappbar.BottomAppBar
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:455)
        at android.app.Activity.setContentView(Activity.java:3468)
        at androidx.activity.ComponentActivity.setContentView(ComponentActivity.java:433)
        at com.example.wellfed.MainActivity.onCreate(MainActivity.java:21)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: android.content.res.Resources$NotFoundException: Drawable com.example.wellfed:drawable/ic_mdi_carrot with resource ID #0x7f0700a0
2022-10-19 23:20:25.571 16067-16067/com.example.wellfed E/AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_mdi_carrot.xml from drawable resource ID #0x7f0700a0
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:891)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:673)
        at android.content.res.Resources.loadDrawable(Resources.java:993)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:983)
        at android.content.res.Resources.getDrawable(Resources.java:922)
        at android.content.Context.getDrawable(Context.java:693)
        at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java:864)
        at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:483)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:149)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:137)
        at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:66)
        at androidx.appcompat.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:509)
        at androidx.appcompat.view.menu.ActionMenuItemView.initialize(ActionMenuItemView.java:131)
        at androidx.appcompat.widget.ActionMenuPresenter.bindItemView(ActionMenuPresenter.java:207)
        at androidx.appcompat.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:188)
        at androidx.appcompat.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:193)
        at androidx.appcompat.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:469)
        at androidx.appcompat.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1178)
        at androidx.appcompat.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:96)
        at androidx.appcompat.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:226)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:292)
        at androidx.appcompat.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1065)
        at androidx.appcompat.view.menu.MenuBuilder.onItemActionRequestChanged(MenuBuilder.java:1115)
        at androidx.appcompat.view.menu.MenuItemImpl.setShowAsAction(MenuItemImpl.java:752)
        at androidx.appcompat.view.SupportMenuInflater$MenuState.setItem(SupportMenuInflater.java:475)
        at androidx.appcompat.view.SupportMenuInflater$MenuState.addItem(SupportMenuInflater.java:531)
        at androidx.appcompat.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:207)
        at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:129)
        at androidx.appcompat.widget.Toolbar.inflateMenu(Toolbar.java:1223)
        at androidx.appcompat.widget.Toolbar.<init>(Toolbar.java:363)
        at com.google.android.material.bottomappbar.BottomAppBar.<init>(BottomAppBar.java:302)
        at com.google.android.material.bottomappbar.BottomAppBar.<init>(BottomAppBar.java:298)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:455)
        at android.app.Activity.setContentView(Activity.java:3468)
        at androidx.activity.ComponentActivity.setContentView(ComponentActivity.java:433)
        at com.example.wellfed.MainActivity.onCreate(MainActivity.java:21)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
2022-10-19 23:20:25.573 16067-16067/com.example.wellfed E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.UnsupportedOperationException: Can't convert to ComplexColor: type=0x1
        at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1152)
        at android.content.res.ResourcesImpl.loadComplexColorFromName(ResourcesImpl.java:1028)
        at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1107)
        at android.content.res.Resources.loadColorStateList(Resources.java:1139)
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:600)
        at android.graphics.drawable.VectorDrawable.updateStateFromTypedArray(VectorDrawable.java:758)
        at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:728)
        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:144)
        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1402)
        at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1361)
        at android.content.res.ResourcesImpl.loadXmlDrawable(ResourcesImpl.java:954)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:877)
        	... 60 more
```
here's the complete log

**Comment by Manpreet-Singh001** [comment]
@steventango the app works fine with API 32, but are we gonna make our app compatible with such a high API??? I think API 30 seems reasonable. let me know what do you think

**Comment by Manpreet-Singh001** [comment]
![image](https://user-images.githubusercontent.com/93985396/196868539-85a4bdf2-1c85-4a7b-afd3-65437eab6c4e.png)
https://developer.android.com/google/play/requirements/target-sdk

it is recommended to use atleast 31 so will we be fine with 32 ?
